# Generated by Django 4.0.5 on 2022-06-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('url', models.URLField(max_length=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField(help_text='ID from source vendor')),
                ('name', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=500)),
                ('share', models.CharField(max_length=500)),
                ('is_baby', models.BooleanField()),
                ('is_legendary', models.BooleanField()),
                ('is_mythical', models.BooleanField()),
                ('forms_switchable', models.BooleanField()),
                ('gender_rate', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creature', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='description', to='monsters.creature')),
            ],
        ),
        migrations.AddIndex(
            model_name='creature',
            index=models.Index(fields=['vendor_id', 'name'], name='monsters_cr_vendor__68e12f_idx'),
        ),
        migrations.AddConstraint(
            model_name='creature',
            constraint=models.UniqueConstraint(fields=('vendor_id', 'name'), name='unique_vendor_identifier'),
        ),
        migrations.AddField(
            model_name='ability',
            name='creature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abilities', to='monsters.creature'),
        ),
    ]
