# Generated by Django 4.0.5 on 2022-06-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='share',
            new_name='shape',
        ),
    ]
